#!/bin/bash
set -euo pipefail

INSTDIR="${XDG_DATA_HOME-$HOME/.local/share}/atlauncher"

if [[ ! -d ${INSTDIR} ]]; then
    mkdir -p $INSTDIR
fi

cd $INSTDIR

if [[ ! -f ${INSTDIR}/ATLauncher.jar ]]; then
    echo "Please reinstall ATlauncher because it was not found on your system." && exit
fi

exec java -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -jar ATLauncher.jar --install-method=deb "$@"
